<?php

declare(strict_types=1);

return [
    "create table users (
        id int unsigned auto_increment primary key,
        name varchar(190) not null,
        email varchar(190) not null unique,
        password_hash varchar(255) not null,
        role enum('super_admin','admin','auditor','client','viewer') not null default 'client',
        status enum('invited','active','disabled') not null default 'invited',
        email_verified_at timestamp null,
        verification_token varchar(100) null,
        reset_token varchar(100) null,
        reset_token_expires_at timestamp null,
        last_login_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table clients (
        id int unsigned auto_increment primary key,
        client_number varchar(100) null,
        abn varchar(30) null unique,
        legal_name varchar(255) not null,
        trading_name varchar(255) null,
        registered_office_address text null,
        billing_email varchar(190) null,
        status enum('active','inactive','archived') not null default 'active',
        notes text null,
        created_at timestamp null,
        updated_at timestamp null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table contacts (
        id int unsigned auto_increment primary key,
        client_id int unsigned not null,
        first_name varchar(100) null,
        last_name varchar(100) null,
        display_name varchar(190) not null,
        email varchar(190) not null,
        phone varchar(100) null,
        position_title varchar(190) null,
        is_active tinyint(1) not null default 1,
        receives_reminders tinyint(1) not null default 1,
        receives_certificates tinyint(1) not null default 1,
        receives_audit_notifications tinyint(1) not null default 1,
        created_at timestamp null,
        updated_at timestamp null,
        index contacts_client_id_index (client_id),
        index contacts_email_index (email),
        index contacts_is_active_index (is_active),
        constraint contacts_client_id_fk foreign key (client_id) references clients(id) on delete cascade
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table client_user (
        id int unsigned auto_increment primary key,
        client_id int unsigned not null,
        user_id int unsigned not null,
        role_for_client enum('primary','representative','billing','evidence_submitter') not null default 'representative',
        approved_by int unsigned null,
        approved_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        unique client_user_unique (client_id, user_id),
        constraint client_user_client_id_fk foreign key (client_id) references clients(id) on delete cascade,
        constraint client_user_user_id_fk foreign key (user_id) references users(id) on delete cascade,
        constraint client_user_approved_by_fk foreign key (approved_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table certification_types (
        id int unsigned auto_increment primary key,
        name varchar(190) not null,
        code varchar(80) not null unique,
        validity_months int not null default 12,
        default_scope_text text null,
        renewal_price_cents int unsigned null,
        stripe_price_id varchar(190) null,
        is_active tinyint(1) not null default 1,
        created_at timestamp null,
        updated_at timestamp null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table audit_criteria (
        id int unsigned auto_increment primary key,
        certification_type_id int unsigned not null,
        version int not null default 1,
        section varchar(190) null,
        reference varchar(190) null,
        title varchar(255) not null,
        requirement_text text not null,
        guidance_text text null,
        evidence_prompt text null,
        sort_order int not null default 0,
        is_required tinyint(1) not null default 1,
        is_active tinyint(1) not null default 1,
        active_from date null,
        active_to date null,
        created_at timestamp null,
        updated_at timestamp null,
        constraint audit_criteria_certification_type_fk foreign key (certification_type_id) references certification_types(id) on delete cascade
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table audits (
        id int unsigned auto_increment primary key,
        audit_number varchar(100) null unique,
        client_id int unsigned not null,
        certification_type_id int unsigned not null,
        auditor_id int unsigned null,
        source enum('imported','renewal_payment','manual') not null default 'manual',
        status enum('draft','awaiting_evidence','submitted','in_review','changes_requested','passed','failed','cancelled') not null default 'draft',
        start_date date null,
        end_date date null,
        due_date date null,
        audit_scope text null,
        overall_client_comment text null,
        overall_auditor_comment text null,
        result enum('pass','fail') null,
        renewal_of_certificate_id int unsigned null,
        stripe_payment_id varchar(190) null,
        created_by int unsigned null,
        submitted_at timestamp null,
        reviewed_at timestamp null,
        completed_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        index audits_client_id_index (client_id),
        index audits_auditor_id_index (auditor_id),
        constraint audits_client_id_fk foreign key (client_id) references clients(id) on delete cascade,
        constraint audits_certification_type_id_fk foreign key (certification_type_id) references certification_types(id),
        constraint audits_auditor_id_fk foreign key (auditor_id) references users(id) on delete set null,
        constraint audits_created_by_fk foreign key (created_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table audit_responses (
        id int unsigned auto_increment primary key,
        audit_id int unsigned not null,
        audit_criterion_id int unsigned not null,
        client_response text null,
        client_status enum('not_started','in_progress','submitted') not null default 'not_started',
        auditor_comment text null,
        auditor_result enum('acceptable','not_acceptable','needs_more_information') null,
        submitted_by int unsigned null,
        submitted_at timestamp null,
        reviewed_by int unsigned null,
        reviewed_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        unique audit_response_unique (audit_id, audit_criterion_id),
        constraint audit_responses_audit_id_fk foreign key (audit_id) references audits(id) on delete cascade,
        constraint audit_responses_criterion_id_fk foreign key (audit_criterion_id) references audit_criteria(id),
        constraint audit_responses_submitted_by_fk foreign key (submitted_by) references users(id) on delete set null,
        constraint audit_responses_reviewed_by_fk foreign key (reviewed_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table audit_evidence_files (
        id int unsigned auto_increment primary key,
        audit_response_id int unsigned not null,
        uploaded_by int unsigned not null,
        original_filename varchar(255) not null,
        stored_path varchar(255) not null,
        mime_type varchar(190) not null,
        size_bytes bigint unsigned not null,
        checksum varchar(128) null,
        description text null,
        uploaded_at timestamp not null default current_timestamp,
        created_at timestamp null,
        updated_at timestamp null,
        constraint audit_evidence_response_id_fk foreign key (audit_response_id) references audit_responses(id) on delete cascade,
        constraint audit_evidence_uploaded_by_fk foreign key (uploaded_by) references users(id)
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table certificates (
        id int unsigned auto_increment primary key,
        certificate_uid varchar(190) not null unique,
        audit_id int unsigned not null,
        client_id int unsigned not null,
        certification_type_id int unsigned not null,
        certificate_number varchar(190) not null unique,
        issue_number int not null default 1,
        status enum('draft','issued','replaced','revoked') not null default 'draft',
        issue_date date not null,
        expiry_date date not null,
        last_day_to_renew date null,
        audit_scope text null,
        docx_path varchar(255) null,
        pdf_path varchar(255) null,
        validation_token varchar(190) null unique,
        generated_by int unsigned null,
        generated_at timestamp null,
        issued_at timestamp null,
        emailed_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        index certificates_client_id_index (client_id),
        index certificates_expiry_date_index (expiry_date),
        constraint certificates_audit_id_fk foreign key (audit_id) references audits(id) on delete cascade,
        constraint certificates_client_id_fk foreign key (client_id) references clients(id) on delete cascade,
        constraint certificates_certification_type_id_fk foreign key (certification_type_id) references certification_types(id),
        constraint certificates_generated_by_fk foreign key (generated_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "alter table audits add constraint audits_renewal_certificate_fk foreign key (renewal_of_certificate_id) references certificates(id) on delete set null",

    "create table email_templates (
        id int unsigned auto_increment primary key,
        template_key varchar(120) not null unique,
        name varchar(190) not null,
        subject varchar(255) not null,
        body_html mediumtext not null,
        body_text mediumtext null,
        merge_fields_json json null,
        is_active tinyint(1) not null default 1,
        created_by int unsigned null,
        updated_by int unsigned null,
        created_at timestamp null,
        updated_at timestamp null,
        constraint email_templates_created_by_fk foreign key (created_by) references users(id) on delete set null,
        constraint email_templates_updated_by_fk foreign key (updated_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table email_logs (
        id int unsigned auto_increment primary key,
        template_id int unsigned null,
        related_type varchar(120) null,
        related_id int unsigned null,
        to_email varchar(190) not null,
        cc_email varchar(190) null,
        bcc_email varchar(190) null,
        subject varchar(255) not null,
        body_html mediumtext null,
        status enum('queued','sent','failed') not null default 'queued',
        provider_response text null,
        sent_at timestamp null,
        failed_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        constraint email_logs_template_id_fk foreign key (template_id) references email_templates(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table reminder_rules (
        id int unsigned auto_increment primary key,
        certification_type_id int unsigned null,
        days_before_expiry int not null,
        template_id int unsigned not null,
        enabled tinyint(1) not null default 1,
        manual_send_allowed tinyint(1) not null default 1,
        created_at timestamp null,
        updated_at timestamp null,
        constraint reminder_rules_certification_type_id_fk foreign key (certification_type_id) references certification_types(id) on delete cascade,
        constraint reminder_rules_template_id_fk foreign key (template_id) references email_templates(id)
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table payments (
        id int unsigned auto_increment primary key,
        client_id int unsigned not null,
        certificate_id int unsigned null,
        audit_id int unsigned null,
        stripe_checkout_session_id varchar(190) null unique,
        stripe_payment_intent_id varchar(190) null,
        amount_cents int unsigned not null,
        currency char(3) not null default 'AUD',
        status enum('pending','paid','failed','refunded') not null default 'pending',
        paid_at timestamp null,
        created_at timestamp null,
        updated_at timestamp null,
        constraint payments_client_id_fk foreign key (client_id) references clients(id) on delete cascade,
        constraint payments_certificate_id_fk foreign key (certificate_id) references certificates(id) on delete set null,
        constraint payments_audit_id_fk foreign key (audit_id) references audits(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table activity_logs (
        id int unsigned auto_increment primary key,
        actor_user_id int unsigned null,
        client_id int unsigned null,
        audit_id int unsigned null,
        certificate_id int unsigned null,
        action varchar(120) not null,
        description text null,
        metadata_json json null,
        ip_address varchar(80) null,
        user_agent varchar(255) null,
        created_at timestamp not null default current_timestamp,
        index activity_logs_action_index (action),
        constraint activity_logs_actor_user_id_fk foreign key (actor_user_id) references users(id) on delete set null,
        constraint activity_logs_client_id_fk foreign key (client_id) references clients(id) on delete set null,
        constraint activity_logs_audit_id_fk foreign key (audit_id) references audits(id) on delete set null,
        constraint activity_logs_certificate_id_fk foreign key (certificate_id) references certificates(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table pending_registrations (
        id int unsigned auto_increment primary key,
        name varchar(190) not null,
        email varchar(190) not null,
        requested_client_name varchar(255) null,
        token varchar(100) null,
        status enum('pending','approved','rejected') not null default 'pending',
        created_at timestamp null,
        updated_at timestamp null,
        unique pending_registrations_email_unique (email)
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table import_runs (
        id int unsigned auto_increment primary key,
        filename varchar(255) not null,
        dry_run tinyint(1) not null default 1,
        status enum('validated','completed','failed') not null,
        summary_json json null,
        error_text text null,
        created_by int unsigned null,
        created_at timestamp not null default current_timestamp,
        constraint import_runs_created_by_fk foreign key (created_by) references users(id) on delete set null
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci",

    "create table reminder_deliveries (
        id int unsigned auto_increment primary key,
        certificate_id int unsigned not null,
        reminder_rule_id int unsigned not null,
        sent_at timestamp not null default current_timestamp,
        unique reminder_delivery_unique (certificate_id, reminder_rule_id),
        constraint reminder_deliveries_certificate_id_fk foreign key (certificate_id) references certificates(id) on delete cascade,
        constraint reminder_deliveries_rule_id_fk foreign key (reminder_rule_id) references reminder_rules(id) on delete cascade
    ) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci"
];
